ln -s ./polkadot/admin/controller/payment/polkadot.php              ./admin-controller-polkadot.php
ln -s ./polkadot/admin/language/en-gb/payment/polkadot.php          ./admin-language-polkadot.php
ln -s ./polkadot/admin/model/payment/polkadot.php                   ./admin-model-polkadot.php
ln -s ./polkadot/admin/view/template/payment/polkadot.twig          ./admin-template.twig
ln -s ./polkadot/catalog/controller/payment/polkadot.php            ./catalog-controller.php
ln -s ./polkadot/catalog/language/en-gb/payment/polkadot.php        ./catalog-language.php
ln -s ./polkadot/catalog/model/payment/polkadot.php                 ./catalog-model.php
ln -s ./polkadot/catalog/view/template/payment/polkadot.twig        ./catalog-template.twig
ln -s ./polkadot/js/DOT.js                                          ./DOT.js
